# Generated by Django 3.0.5 on 2025-05-07 19:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0018_auto_20201015_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='mobile',
            field=models.CharField(max_length=11, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid Bangladeshi phone number (e.g., 01712345678) \n-> It should start with 01 and be followed by 9 digits.', regex='^01[3-9]\\d{8}$')]),
        ),
        migrations.AlterField(
            model_name='patient',
            name='mobile',
            field=models.CharField(max_length=11, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid Bangladeshi phone number (e.g., 01712345678) \n-> It should start with 01 and be followed by 9 digits.', regex='^01[3-9]\\d{8}$')]),
        ),
    ]
