# Generated by Django 3.0.5 on 2025-05-08 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0019_auto_20250508_0124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='appointmentDate',
        ),
        migrations.AddField(
            model_name='appointment',
            name='appointment_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Appointment date & time'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='doctorId',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='doctorName',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='patientId',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='patientName',
            field=models.CharField(max_length=200),
        ),
    ]
