# Generated by Django 3.0.5 on 2025-05-09 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0021_room_roomrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='capacity',
            field=models.PositiveIntegerField(default=1, help_text='Total beds of this type in hospital'),
        ),
        migrations.AddField(
            model_name='roomrequest',
            name='duration_hours',
            field=models.PositiveIntegerField(default=24),
        ),
        migrations.AddField(
            model_name='roomrequest',
            name='start_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
