# Generated by Django 3.0.5 on 2025-05-09 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0022_auto_20250509_0605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10),
        ),
    ]
