# Generated by Django 3.0.5 on 2025-05-09 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0023_auto_20250509_0929'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomrequest',
            name='assigned_room',
            field=models.CharField(blank=True, help_text='Room number assigned by admin upon approval', max_length=10),
        ),
    ]
