# Generated by Django 3.0.5 on 2025-05-12 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0024_roomrequest_assigned_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdischargedetails',
            name='OtherCharge',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='patientdischargedetails',
            name='daySpent',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='patientdischargedetails',
            name='doctorFee',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='patientdischargedetails',
            name='medicineCost',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='patientdischargedetails',
            name='roomCharge',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='patientdischargedetails',
            name='total',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
